### ISSUE TITLE
Comment / Uncomment multiple lines [$20]

### ISSUE THREAD

**Issue by epgfm** [mate-desktop/pluma#206]
It'd be nice to be able to comment out / uncomment a selection of lines in one go.
This is one feature I often regret not having.
Comment characters can be inferred from the active highlight style.

**Comment by Yetoo1** [comment]
Should this be built in or as a separate package like gedit does?

**Comment by epgfm** [comment]
@Yetoo1 anyway is fine, I can't judge what would be best but I really only care about the feature being available.

**Comment by Yetoo1** [comment]
@epgfm I found this [Github](https://github.com/yselkowitz/pluma-plugins) which gives the ability to compile a selected plugin.

**Comment by elcste** [comment]
@Yetoo1 It [doesn't look like](https://github.com/yselkowitz/pluma-plugins/issues/6) it works with GTK+ 3 pluma.

**Comment by alexeyneu** [comment]
#383

**Comment by alexeyneu** [comment]
may be close it?

**Comment by sc0w** [comment]
seems in `xed` the feature was done in https://github.com/linuxmint/xed/pull/290

**Comment by mbkma** [comment]
This issue can be closed, because a code comment plugin exists in https://github.com/mate-desktop/pluma-plugins.
@raveit65 I do not need the bounty, the MATE Desktop team can claim it. Maybe it would be good to claim it soon because Bountysource may keep the money if you wait too long :/ (see https://simon.shimmerproject.org/2020/06/18/why-bountysource-why/)

**Comment by raveit65** [comment]
Ok,  will try to claim it for the team.
