### ISSUE TITLE
Ctrl + L doesn't open a location

### ISSUE THREAD

**Issue by Yetoo1** [mate-desktop/pluma#210]
I was reading through the shortcuts and testing each one. This shortcut doesn't open anything. This was tested with 1.17.3 or whatever is currently in the master branch at the time of posting.

**Comment by monsta** [comment]
Help is really outdated... That feature was removed from gedit [in 2009](https://git.gnome.org/browse/gedit/commit/?id=26c2dfbd90b2f973f8540b15be4da38216e3a70b) but they never cleaned up the docs, so we inherited that part.

**Comment by raveit65** [comment]
Closing, because this feature is in GtkFileChooser (open file) dialog.
We can switch between location entry and breadcrumbs with `ctrl+l`, then we can open a relative file location like `~/test.txt`.

Edit screenshot:

<img width="994" alt="Captura de Pantalla 2020-04-16 a les 16 43 24" src="https://user-images.githubusercontent.com/10171411/79470230-72595080-8001-11ea-8c93-dc610bfcac67.png">

**Comment by raveit65** [comment]
And `help` page is updated.
https://github.com/mate-desktop/pluma/commit/b6d827c00b671daa5ed37b9074f4f4bb4f06cfb9
