### ISSUE TITLE
[Feature Request]: Switch tabs with CTRL+TAB [$30]

### ISSUE THREAD

**Issue by epgfm** [mate-desktop/pluma#211]
It'd be nice to be able to switch open tabs the same way we can for Firefox: CTRL+TAB. and CTRL+SHIFT+TAB for reverse switch.
Currently we can only switch using ALT+SHIFT+NUMBER (so it's absolute switching with a hard limit of 10 tabs)

**Comment by samtygier** [comment]
Pluma can switch tabs with CTRL+ALT+PgUp and CTRL+ALT+PgDn
Mate Terminal and Caja use CTRL+PgUp and CTRL+PgDn

So should should they all be changed to CTRL+TAB and CTRL+SHIFT+TAB to match Firefox? or should CTRL+TAB and CTRL+SHIFT+TAB be added as additional keyboard shortcuts? If so should pluma drop the need for ALT?

**Comment by epgfm** [comment]
The way I see it, the Firefox shortcuts are now the expected, "natural" ones.
If someone really wants to hang on to the current shortcuts, maybe a way to configure the keybinding would be better.

**Comment by samtygier** [comment]
Looking into this it seems like gtk reserves CTRL+TAB for changing focus between widgets. https://bugzilla.gnome.org/show_bug.cgi?id=123994 . So for example if you have the text area focused, then CTRL+TAB lets you focus the tool bar. There may be uses who can't use a mouse dependant on this.

As mentioned on that bug, pidgin bypasses this, by intercepting all keypress and handling the CTRL+TAB case. So it is possible, just a little hacky.

**Comment by raveit65** [comment]
CTRL+TAB is used for switching between applications too. So this can be confuse if pluma isn't a maximize window and isn't focus.
In result you need to use CTRL+TAB 2 times. One time for selecting the plum window and than for switching the tabs.
So i would prefer to use the same keys like caja or mate-terminal.
Btw. not everyone is using firefox, so why follow them?

**Comment by epgfm** [comment]
You're using CTRL+TAB to switch applications? I thought the universal shortcut for that was ALT+TAB. Anyway, that's not only Firefox using CTRL+TAB to switch between panel, Google Chrome does too, and Opera.

**Comment by raveit65** [comment]
I edid previous comment.

**Comment by raveit65** [comment]
Btw. volunteers welcome

**Comment by raveit65** [comment]
I agree with follow using firefox shortcuts, but using both the old ones and new ones seems a bit overload for me.
For all 3 applications.

**Comment by epgfm** [comment]
@raveit65 should we also open an issue for mate-terminal?

**Comment by raveit65** [comment]
yeah, for the record :-)

**Comment by raveit65** [comment]
@flexiondotorg @monsta 
Thoughts?

**Comment by alexarnaud** [comment]
Le 08/08/2017 à 10:37, raveit65 a écrit :
> @flexiondotorg <https://github.com/flexiondotorg> @monsta 
> <https://github.com/monsta>
> Thoughts?

For now, applications follow the GTK shortcut. It should be a proper way 
to allow user in the keyboard settings to use ctrL+tab and 
ctrl+shift+tab instead of ctrl+pgup and ctrl+pgdown to change the 
default GTK config.
Another option should be to allow user to override the default GTK 
settings inside Pluma.

That what I have inside my GTK3 config:
> @binding-set NoCtrlTab
> {
> 	unbind "<Primary>Tab";
> 	unbind "<Primary><Shift>Tab";
> }
> 
> /* GTK < 3.20 */
> GtkNotebook * {
> 	gtk-key-bindings: NoCtrlTab;
> }
> /* GTK >= 3.20 */
> notebook * {
> 	-gtk-key-bindings: NoCtrlTab;
> }
> 
> @binding-set SwitchPage
> {
> 	bind "<Primary>Tab" { "change-current-page" (1) };
> 	bind "<Primary><Shift>Tab" { "change-current-page" (-1) };
> }
> 
> /* GTK < 3.20 */
> GtkNotebook {
> 	gtk-key-bindings: SwitchPage;
> }
> /* GTK >= 3.20 */
> notebook {
> 	-gtk-key-bindings: SwitchPage;
> }

Best regards.
-- 
Alex ARNAUD
Visual-Impairment Project Manager
Hypra - "Humanizing technology"

**Comment by snaiperskaya96** [comment]
Please have a look at this PR https://github.com/mate-desktop/pluma/pull/243 :)

**Comment by sc0w** [comment]
if we use ctrl+tab to switch tabs, how to access to the toolbar/sidepane only with keyboard?

**Comment by raveit65** [comment]
I have the feeling that switching to ctrl+tab breaks accessibility support.
Especially 'ctrl+tab and ctrl+shift+tab' are used by ppl with visual impairment for tabbing trough an application, in all applications.
This is a **MUST**, we shouldn't break this.

**Comment by lukefromdc** [comment]
Since I've never gotten into the habit of using keyboard tab switching on Firefox, I'm basically neutral on this. I can see though how different apps working different ways would confuse new users.  Two expectations they would bring: how does Firefox do it, and how does MS Windows do it. For that matter, are Firefox and Chrome keybindings consistant? FF has a shrinking userbase by percentage both due to the rise of Chrome and the rise of Android(which pushed Chrome). Firefox though probably has and probably will retain a high userbase with LInux users as it is designed to be user-configurable to a far greater extent than Chrome and distros are keeping it.

**Comment by elcste** [comment]
@lukefromdc I just tried these this afternoon: Chrome on Linux and Windows (and Mac) use control+tab to switch tabs too. Same for Edge on Win 10, Sublime Text (Linux and Windows), and Notepad++, the Windows text editor. (Sublime Text seems to switch in something like last used order by default). Also the same for KDE's editor kate and dolphin file manager.

**Comment by uvwild** [comment]
I vote for ctrl-tab also. 
Obviously, the PgU/D sucks badly
One hand vs two with PageDown.
Or at least expose it in configuration!

**Comment by am-225** [comment]
It's been almost 5 years now, on my side pluma still relies on pgUP/DOWN to switch tabs, any updates?

**Comment by Yetoo1** [comment]
@am-225 I think you need to set org.mate.pluma.ctrl-tab-switch-tabs as indicated by this commit: https://github.com/mate-desktop/pluma/commit/98edfd338d1248d386fc211f27252d5fb9053dc9.
