### ISSUE TITLE
Regexp replace cannot use "\1"

### ISSUE THREAD

**Issue by hanaokaiwa** [mate-desktop/pluma#254]
#### Expected behaviour
regexp replace with "\1" should use the first subpartition

#### Actual behaviour
regexp replace with "\1" uses string "\1"

#### MATE general version
mate-desktop-1.18.0-5.fc26.x86_64

#### Package version
pluma-1.18.2-1.fc26.x86_64

#### Linux Distribution
Fedora 26

**Comment by barkovv** [comment]
By all means it's a bug. Now the algorithm is: 
 - find the match for "Search for" pattern
 - select the match in document
 - delete the match from document
 - insert the content of "Replace with:"
Now this workflow can be improved with g_regex_replace () (see https://developer.gnome.org/glib/stable/glib-Perl-compatible-regular-expressions.html#g-regex-replace). This will fix the "\1" problem same as other similar backreferences.

**Comment by monsta** [comment]
Ok, would be nice to get it fixed. We'd put the fix into the next 1.18.x release then.

**Comment by barkovv** [comment]
I've made some changes to fix it.
Test case:
 - document_content: "1 2 3 4 5"
 - search_for: "\d"
 - replace_with: "!\0"
 - document_after: "!1 !2 !3 !4 !5"

If @hanaokaiwa provide some more test cases, I'll use them to find our if my fix is correct.

**Comment by dp-alvarez** [comment]
There is still a slight bug related to this. The "parse escape sequences" checkbox should have no effect if the "match regular expression" checkbox is ticked, both the search and replace strings should be passed on without any processing regarding backslashes (or any other character).
However the current behavior is confusing. The "search for" field is only correctly interpreted if the "parse escape sequences" is unticked and the "replace with" field is only corretly interpreted if the "parse escape sequences" IS ticked.
For example, backreferences only work with "parse escape sequences" ticked, otherwise it replaces backrefences with the literal text "\1". Searching for the "\\n" regex however (which searches for the literal text "\n") only works with "parse escape sequences" unticked.

I guess there is different processing for escape sequences in each field, the likely solution is to completely disable both of them if "match regular expression" is checked.
