### ISSUE TITLE
Repo management request

### ISSUE THREAD

**Issue by PyroSamurai** [mate-desktop/pluma#521]
I'm sure this is overly forward of me, but as a user who wishes to contribute code I felt I had to say something.

I think it would be beneficial to move the plugins folder to its own repo.
Perhaps "pluma-plugins", that seems popular with your plugin porters.
The majority of the issues relate to the plugins and drown out the core application problems, so it would be good separate them. You could use gitmodules to pull it in if it is really necessary, but it would be best to make them standalone.

Another suggestion I have is to implement some type of mandatory styling settings for code.
Some styling choices:
- AStyle: very stable, settings don't change often, setting input is short (mine: astyle -A1xC76Ucns4)
- Uncrustify: style settings down to the  last detail, very actively developed so settings change often
- EditorConfig: the other choice, useful for git novices, works for any file type (ex: Markdown)
- gitattributes: can only really enforce tab->spaces and EOL characters

Developers like to read/write code in their own particular style. Having a predifined styling allows developers to switch the code to their preferred style for maximum programming efficiency and then instantly switch the code back when they are ready to make a commit.

Anyways, these might be big changes but I think they are needed.
The second one in particular will reduce the trouble for non-member contributions.

Only the best of intentions here :)
If there are reasons these haven't been done already, I will be glad to listen and understand them.

**Comment by lukefromdc** [comment]
I don't see requiring all coders to eun commits through automated styling
tools some may not have installed working. I edit in Pluma and do everything
by hand, so can follow a template but don't have automation for it.

**Comment by PyroSamurai** [comment]
@lukefromdc These are terminal tools, most of which have integration options with your git tools.
They are all cross-platform as well. I don't think it would be hard to implement.
Plus, I assume most of your code contributors (programmers) are completely capable of installing and running such a program.

**Comment by lukefromdc** [comment]
I just do NOT see this happening  it would be a barrier to new contributors and
to some existing contributors (myself included). No problem with people using these,
but when I first.started I had to use the web interface to edit files on my branch.
I am opposed to rejecting all commits that have not passed through these tools,
to the point I probably could no longer participate myself.

**Comment by vkareh** [comment]
I'm not opposed to styling tools, as long as the team agrees. I think we have a relatively sane approach currently, with the exception of mixed tabs and spaces. The main issue with a big code reformatting is losing contextual git annotations (they're there, but harder to access). I would keep whatever changes to a minimum (like keeping the current style but standardizing on tabs/spaces approach) for this same reason.

I personally lean toward smart tabs (tabs for indentation, spaces for alignment). This looks correct in all IDEs and editors, and allows each developer their own local configuration. But mostly I just follow the current style of the surrounding code.

Another thing is backporting from GNOME. Sticking to their format makes backporting easier, generally speaking. But this shouldn't be a blocker either.

I use vim for all programming, so these tools should all be easy to integrate, but in many cases unnecessary, as we can just have a script in our dev tools repo, or as a git hook.

Regarding plugins, sounds reasonable, but again, the team has to agree on a strategy. I personally feel that git modules are a strange beast, but in this case might allow us to keep the same build processes we currently have while having the plugins in a different repo.

**Comment by PyroSamurai** [comment]
@vkareh as long as I can set it with a styler, I don't care much what it looks like in the repo. It'll allow me to use my own style while I work on it.

You're right about gitmodules being a strange beast, which is why I recommend full separation if possible.

**Comment by raveit65** [comment]
I don't like the uses tabs in code and our codestyling is to use spaces, see wikki.
Honestly. i don't get why you can't contribute without asking us to change our repo settings.
I don't like unneeded extra work.

**Comment by vkareh** [comment]
> I don't like the uses tabs in code and our codestyling is to use spaces, see wiki.

That's true, tabs are pretty much broken in many parts of our code, so we should really default to just spaces. Currently I just follow whichever style is used by the code I'm working on. I dislike bad indentations, but I also dislike mixed-style code even more.

>  Honestly. i don't get why you can't contribute without to change our repo settings.

This is also true. I understand the sentiment behind @PyroSamurai's request, but not sure how the code style would prevent you from contributing. Any modern editor/IDE will adapt to the current file (unless you do everything by hand, in which case you probably don't care about automatic styles anyway).

Also, for the same reasons mentioned above, I don't want a big reformat of the entire code. My text editor happily adapts to the style of the current file, and I get to see the git blame of each line as I'm looking at the code. A massive reformat will reset those annotations to an irrelevant commit. Also, any legacy code would instantly become harder to backport fixes for, as most of our code style comes from the old GNOME developers, and git relies on this for code comparison.

@PyroSamurai, keep in mind that most of our code is around 20 years old, so we've had literally decades and thousands of developers contributing since the days of GNOME, some following the rules, some not. This has led to the current state of our code, and doing a sweeping change of the code style is not necessarily in our best interest at this point. Also, considering the history of our code, I would say that code style has not been an issue for getting developers to contribute.

That said, the request regarding Pluma plugins might be worth exploring for a future release. The current set up makes it seem as though only plugins inside our repo would work, when the reality is that anyone can write a plugin and host it wherever they want.

I think the main issue here is documentation.

Regarding Pluma issues being mostly about plugins, even if we move the plugins out, people will still report bugs here, and then we'll have to deal with _two_ repos where we track issues about our pluma and its plugins. So we need to weigh the pros and cons of doing this...

**Comment by raveit65** [comment]
About plugins.
Splitting the few plugins to an extra package will give us more work to maintain and release the package. Also distro-maintainers will have to add one package more to their workload.
Shipping all with one package will make sure that those plugins are installed and not forgotten by a user or distro-maintainer.

And keep in mind that the gedit-plugins package with a lot of more pugins was only forked to Mate with gtk2, Those repos at github were never updated to gtk+3 or python3.

**Comment by PyroSamurai** [comment]
I wish to continue to hear the opinions of the other big contributors as well. :)
I do know one thing: that the best way to reduce management work is the through automation of tasks.

**Comment by lukefromdc** [comment]
I do in fact do everything by hand, both because I am used to working that way and because some tools (I don't know which ones) are distributed as closed blobs. I can follow any style template asked so long as I am NOT requires to show evidence of running the files through tools I don't have.

**Comment by PyroSamurai** [comment]
No one is asking you to use a tool, even though it would be easier, just replicate the output. Strictly.
Source code is available for all the suggested tools, no blobs used. Do you have any other problems?
My suggestions are only for the pluma repo, despite the fatalistic attitude here, it is doable.

**Comment by vkareh** [comment]
@PyroSamurai, I think part of the "fatalistic attitude" comes form this:

> implement some type of mandatory styling settings for code

The idea that we have to use mandatory styling, provided by some tool that may or may not be available in our IDE of choice, is strange. How long has that tool been available? How widely known/distributed is it? MATE's source code is far older than _all_ the tools you mentioned above, which begs the question of whether those tools will still be available in a few years as MATE continues chugging along happily?

Our current indentation/alignment style has been sufficient for MATE and I doubt that it has hindered any meaningful developer contributions in any way... most IDEs adapt happily. Also, different projects in MATE come from different places and have different styles - are you proposing we swap the style of _all_ those projects to satisfy this new requirement? Do we need to also do this for any new project we fork/inherit? Or if we do it for _just_ Pluma, are you then advocating for fragmenting the code style even further, with Pluma being now more different than others?

The point is, @PyroSamurai, that this is a solution in look for a problem that we don't seem to have. Changing the coding style of MATE is a _huge_ undertaking with very dubious gains. If we can get some real data regarding the benefits of doing this, and how this will affect the future of MATE developers/contributors, and a plan for tool obsolency, and someone wishes to take on this work, then there might be value in exploring it. Until then, the limited time our developers have is most likely better spent in fixing bugs, adding features, maintaining the software, and upgrading library support, rather than trying to bikeshed on whether tabs are better than spaces and what color we want our variables to be.

**Comment by PyroSamurai** [comment]
@vkareh I understand. You have made it clear to me that modernizing is not in MATE's future. As for tabs and spaces, https://wiki.mate-desktop.org/#!pages/code_style.md specifies spaces are to be used yet there are many tabs in the code. You don't seem to enforce it. Styling any amount of code with a tool is a 30 second job. I am sad that I could not help you see the value in my ideas, but that is my own failing. I hope the best of luck for the project. :)

**Comment by vkareh** [comment]
Thanks, no hard feelings. Modernizing is absolutely one of our driving forces, but we just don't have the bandwidth to enforce it when it comes to code styling, unfortunately.

**Comment by PyroSamurai** [comment]
@vkareh The [Restyled.io Github App](https://github.com/marketplace/restyled-io/plan/MDIyOk1hcmtldHBsYWNlTGlzdGluZ1BsYW4yNTU0) might help MATE keep up with its current style and reduce management workload. Not continuing the thread, just giving you a helpful link. :)
